import{AiFillStar}from "react-icons/ai";

const data = [
    {
        img:"/abdostore/src/Images/WhatsApp_Image_2024-12-19_at_12.48.35_PM__1_-removebg-preview.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },   
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },   
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },
    {
        img:"Images/purepng.com-running-shoesrunning-shoesrunningshoessportingphysical-activitiesstyle-1701528181286yu8rs.png",
        title:"Nike Air Monarch IV",
        star:<AiFillStar className="rating-star"/>,
        review:"(123 reviews)",
        prevprice:"$140,00",
        newprice:"200",
        company:"Nike",
        color:"white",
        category:"sneakers",
    },

]